// src/database/schema.ts
import {
  pgTable, text, timestamp, boolean, integer, date, time, jsonb, pgEnum,
  index, uniqueIndex, primaryKey, check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { nanoid } from "nanoid";

// ── Better Auth owns user/session/account/verification ───────────────────────
export const staffRole = pgEnum("staff_role", ["admin", "dentist", "assistant", "secretary"]);

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").$defaultFn(() => false).notNull(),
  image: text("image"),
  role: staffRole("role").notNull().default("assistant"),   // additionalField, input: false
  isActive: boolean("is_active").notNull().default(true),   // additionalField, input: false
  title: text("title"),                                     // "Chirurgien-Dentiste" — printed on ordonnances
  inpe: text("inpe"),                                       // practitioner national id, on feuilles de soins
  color: text("color").notNull().default("#0D9488"),        // agenda tint
  createdAt: timestamp("created_at").$defaultFn(() => new Date()).notNull(),
  updatedAt: timestamp("updated_at").$defaultFn(() => new Date()).notNull(),
});

// session, account, verification — generated by the Better Auth CLI, copied verbatim.
// The `user` table above keeps its own role/isActive/title/inpe/color columns; the CLI
// emits `role` as text, ours is the staff_role enum. relations() helpers are omitted:
// nothing in this schema uses them and the Drizzle adapter does not consume them.
export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [index("session_userId_idx").on(t.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (t) => [index("account_userId_idx").on(t.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (t) => [index("verification_identifier_idx").on(t.identifier)],
);

// ── Enums ────────────────────────────────────────────────────────────────────
export const genderType        = pgEnum("gender", ["male", "female"]);
export const dentitionType     = pgEnum("dentition", ["adult", "child"]);
export const treatmentStatus   = pgEnum("treatment_status", ["planned", "in_progress", "completed", "canceled"]);
export const appointmentStatus = pgEnum("appointment_status", ["planned", "confirmed", "arrived", "completed", "canceled", "no_show"]);
export const paymentMethod     = pgEnum("payment_method", ["cash", "check", "card", "transfer", "insurance"]);
export const documentType      = pgEnum("document_type", ["facture", "devis", "feuille_de_soins", "ordonnance", "certificat"]);
export const serviceCategory   = pgEnum("service_category", [
  "consultation", "restorative", "endodontics", "prosthetics", "surgery",
  "orthodontics", "periodontics", "implantology", "cosmetic", "other",
]);
export const expenseCategory   = pgEnum("expense_category", [
  "supplies", "lab", "rent", "utilities", "salaries", "equipment", "maintenance", "taxes", "other",
]);
export const smokingStatus     = pgEnum("smoking_status", ["none", "occasional", "regular"]);
export const bloodType         = pgEnum("blood_type", [
  "a_pos", "a_neg", "b_pos", "b_neg", "ab_pos", "ab_neg", "o_pos", "o_neg",
]);

// ── Clinic settings: exactly one row, id = "clinic" ──────────────────────────
export const clinicSettings = pgTable("clinic_settings", {
  id: text("id").primaryKey().default("clinic"),
  name: text("name").notNull(),
  address: text("address"),
  city: text("city"),
  phone: text("phone"),
  email: text("email"),
  ice: text("ice"), patente: text("patente"), fiscalId: text("fiscal_id"),
  cnssNumber: text("cnss_number"), inpe: text("inpe"),
  logoUrl: text("logo_url"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ── Insurers («mutuelles») — configurable, not an enum ───────────────────────
export const insurers = pgTable("insurers", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  name: text("name").notNull(),                    // CNSS, CNOPS, SANLAM, RMA, AXA…
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ── Tags — configurable patient labels ──────────────────────────────────────
export const tags = pgTable("tags", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  label: text("label").notNull(),                  // Urgent, Sensible, VIP, Famille…
  color: text("color").notNull().default("#0D9488"),
  icon: text("icon"),                              // lucide icon name
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const patientTags = pgTable("patient_tags", {
  patientId: text("patient_id").notNull().references(() => patients.id, { onDelete: "cascade" }),
  tagId: text("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }),
}, (t) => [primaryKey({ columns: [t.patientId, t.tagId] })]);

// ── Patients ─────────────────────────────────────────────────────────────────
export const patients = pgTable("patients", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  shortCode: text("short_code").notNull().unique(),     // "W6U8" — 4 chars, app-generated
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  phone: text("phone").notNull(),                       // E.164 +212XXXXXXXXX
  secondaryPhone: text("secondary_phone"),
  email: text("email"),
  birthDate: date("birth_date", { mode: "string" }),
  gender: genderType("gender"),
  address: text("address"),
  city: text("city"),
  cin: text("cin"),
  profession: text("profession"),
  insurerId: text("insurer_id").references(() => insurers.id, { onDelete: "set null" }),
  insuranceNumber: text("insurance_number"),
  allergies: text("allergies"),
  medicalNotes: text("medical_notes"),
  isArchived: boolean("is_archived").notNull().default(false),
  createdByStaffId: text("created_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  index("patients_last_name_idx").on(t.lastName),
  index("patients_phone_idx").on(t.phone),
  index("patients_archived_idx").on(t.isArchived),
]);

// ── Medical history («dossier médical») — at most one row per patient ───────
// Absent row ⇒ never filled, which the UI must tell apart from «filled, nothing
// to report». `conditions` holds English keys validated by Zod; the French
// copy lives in the patients slice's constants.ts.
// `pregnancyWeeks` is the term AS OF `updatedAt` — readers age it forward.
export const medicalHistories = pgTable("medical_histories", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  patientId: text("patient_id").notNull().unique().references(() => patients.id, { onDelete: "cascade" }),
  conditions: jsonb("conditions").$type<string[]>().notNull().default([]),
  onAnticoagulants: boolean("on_anticoagulants").notNull().default(false),
  onBisphosphonates: boolean("on_bisphosphonates").notNull().default(false),
  needsAntibioticProphylaxis: boolean("needs_antibiotic_prophylaxis").notNull().default(false),
  isPregnant: boolean("is_pregnant"),                   // null = not asked / not applicable
  pregnancyWeeks: integer("pregnancy_weeks"),
  isBreastfeeding: boolean("is_breastfeeding"),
  currentMedications: text("current_medications"),
  surgicalHistory: text("surgical_history"),            // antécédents chirurgicaux / hospitalisations
  anesthesiaReactions: text("anesthesia_reactions"),
  smoking: smokingStatus("smoking").notNull().default("none"),
  bruxism: boolean("bruxism").notNull().default(false),
  bloodType: bloodType("blood_type"),
  primaryDoctorName: text("primary_doctor_name"),       // médecin traitant
  primaryDoctorPhone: text("primary_doctor_phone"),
  emergencyContactName: text("emergency_contact_name"), // a parent, for a child
  emergencyContactPhone: text("emergency_contact_phone"),
  emergencyContactRelation: text("emergency_contact_relation"),
  updatedByStaffId: text("updated_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, () => [
  // A term outside 1–42 SA is a typo, whichever client wrote it.
  check(
    "medical_histories_pregnancy_weeks_range",
    sql`pregnancy_weeks IS NULL OR pregnancy_weeks BETWEEN 1 AND 42`,
  ),
]);

// ── Services («actes» catalogue) — billing ──────────────────────────────────
export const services = pgTable("services", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  label: text("label").notNull(),
  category: serviceCategory("category").notNull().default("other"),
  defaultPriceCents: integer("default_price_cents").notNull().default(0),
  durationMinutes: integer("duration_minutes").notNull().default(30),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [index("services_category_idx").on(t.category)]);

// ── Appointment types — calendar, separate from billing ─────────────────────
export const appointmentTypes = pgTable("appointment_types", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  label: text("label").notNull(),               // Consultation Initiale, Chirurgie, Prothèse…
  color: text("color").notNull().default("#0D9488"),
  defaultDurationMinutes: integer("default_duration_minutes").notNull().default(30),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ── Practitioner weekly schedules. ISO weekday: 1 = lundi … 7 = dimanche ────
export const practitionerSchedules = pgTable("practitioner_schedules", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  practitionerId: text("practitioner_id").notNull().references(() => user.id, { onDelete: "cascade" }),
  weekday: integer("weekday").notNull(),
  startTime: time("start_time").notNull(),
  endTime: time("end_time").notNull(),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [index("practitioner_schedules_idx").on(t.practitionerId, t.weekday)]);

// practitionerId NULL ⇒ clinic-wide closure. Cascade, NOT set null:
// a deleted practitioner's leave must not become a clinic closure.
export const scheduleExceptions = pgTable("schedule_exceptions", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  practitionerId: text("practitioner_id").references(() => user.id, { onDelete: "cascade" }),
  startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
  endsAt: timestamp("ends_at", { withTimezone: true }).notNull(),
  reason: text("reason"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [index("schedule_exceptions_starts_at_idx").on(t.startsAt)]);

// ── Appointments — staff-created only ───────────────────────────────────────
export const appointments = pgTable("appointments", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  patientId: text("patient_id").notNull().references(() => patients.id, { onDelete: "cascade" }),
  practitionerId: text("practitioner_id").references(() => user.id, { onDelete: "set null" }),
  typeId: text("type_id").references(() => appointmentTypes.id, { onDelete: "set null" }),
  startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
  endsAt: timestamp("ends_at", { withTimezone: true }).notNull(),
  status: appointmentStatus("status").notNull().default("planned"),
  reason: text("reason"),
  notes: text("notes"),
  createdByStaffId: text("created_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  index("appointments_starts_at_idx").on(t.startsAt),
  index("appointments_practitioner_starts_at_idx").on(t.practitionerId, t.startsAt),
  index("appointments_patient_idx").on(t.patientId),
]);

// ── Treatments («actes»). label + price are SNAPSHOTS from the service. ─────
export const treatments = pgTable("treatments", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  patientId: text("patient_id").notNull().references(() => patients.id, { onDelete: "cascade" }),
  appointmentId: text("appointment_id").references(() => appointments.id, { onDelete: "set null" }),
  serviceId: text("service_id").references(() => services.id, { onDelete: "set null" }),
  practitionerId: text("practitioner_id").references(() => user.id, { onDelete: "set null" }),
  label: text("label").notNull(),
  teeth: jsonb("teeth").$type<string[]>().notNull().default([]),   // FDI codes
  totalAmountCents: integer("total_amount_cents").notNull().default(0),
  status: treatmentStatus("status").notNull().default("planned"),
  performedAt: timestamp("performed_at", { withTimezone: true }),
  notes: text("notes"),
  createdByStaffId: text("created_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  index("treatments_patient_idx").on(t.patientId),
  index("treatments_performed_at_idx").on(t.performedAt),
]);

// ── Payments. treatmentId nullable: payments land on the patient account, ───
//    allocation to an acte is optional.
export const payments = pgTable("payments", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  patientId: text("patient_id").notNull().references(() => patients.id, { onDelete: "cascade" }),
  treatmentId: text("treatment_id").references(() => treatments.id, { onDelete: "set null" }),
  insurerId: text("insurer_id").references(() => insurers.id, { onDelete: "set null" }),
  amountCents: integer("amount_cents").notNull(),
  method: paymentMethod("method").notNull().default("cash"),
  paidAt: timestamp("paid_at", { withTimezone: true }).notNull().defaultNow(),
  reference: text("reference"),
  notes: text("notes"),
  createdByStaffId: text("created_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  index("payments_patient_idx").on(t.patientId),
  index("payments_treatment_idx").on(t.treatmentId),
  index("payments_paid_at_idx").on(t.paidAt),
]);

// ── Expenses — ADMIN ONLY end to end ────────────────────────────────────────
export const expenses = pgTable("expenses", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  label: text("label").notNull(),
  category: expenseCategory("category").notNull().default("other"),
  amountCents: integer("amount_cents").notNull(),
  spentAt: timestamp("spent_at", { withTimezone: true }).notNull().defaultNow(),
  supplier: text("supplier"),
  notes: text("notes"),
  createdByStaffId: text("created_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [index("expenses_spent_at_idx").on(t.spentAt)]);

// ── Generated documents registry ────────────────────────────────────────────
export const documents = pgTable("documents", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  patientId: text("patient_id").notNull().references(() => patients.id, { onDelete: "cascade" }),
  type: documentType("type").notNull(),
  fileName: text("file_name").notNull(),
  storageUrl: text("storage_url").notNull(),
  generatedByStaffId: text("generated_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (t) => [
  index("documents_patient_idx").on(t.patientId),
  index("documents_created_at_idx").on(t.createdAt),
]);

// ── Odontogram: one row per patient per dentition, plus two layers ──────────
// `initial` = situation initiale, `current` = état après actes. Both opaque.
export const odontogramCharts = pgTable("odontogram_charts", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  patientId: text("patient_id").notNull().references(() => patients.id, { onDelete: "cascade" }),
  dentition: dentitionType("dentition").notNull().default("adult"),
  initial: jsonb("initial").$type<Record<string, unknown>>().notNull().default({}),
  current: jsonb("current").$type<Record<string, unknown>>().notNull().default({}),
  updatedByStaffId: text("updated_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [uniqueIndex("odontogram_patient_dentition_idx").on(t.patientId, t.dentition)]);

// ── Tasks («liste des tâches») — clinic-wide, not per-user ──────────────────
export const tasks = pgTable("tasks", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  content: text("content").notNull(),
  dueDate: date("due_date", { mode: "string" }),
  isImportant: boolean("is_important").notNull().default(false),
  isDone: boolean("is_done").notNull().default(false),
  createdByStaffId: text("created_by_staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ── Activity log («activité du jour») ───────────────────────────────────────
export const activityLog = pgTable("activity_log", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  entityType: text("entity_type").notNull(),      // "appointment" | "treatment" | "payment" | "document"
  entityId: text("entity_id").notNull(),
  action: text("action").notNull(),               // "created" | "updated" | "status_changed" | "generated"
  summary: text("summary").notNull(),             // French sentence rendered verbatim
  staffId: text("staff_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (t) => [index("activity_log_created_at_idx").on(t.createdAt)]);
